#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PORT="${PORT:-/dev/ttyUSB0}"
BOARD="esp32:esp32:esp32"

echo "Compilando..."

arduino-cli compile \
    --fqbn "$BOARD" \
    "$SCRIPT_DIR"

echo "Atualizando ESP32 na porta $PORT..."

arduino-cli upload \
    -p "$PORT" \
    --fqbn "$BOARD" \
    "$SCRIPT_DIR"

echo "Ok"

arduino-cli monitor \
    -p "$PORT" \
    -c baudrate=115200
